networks:
  default:
    driver: bridge
    name: roboshop

services:
  mongodb:
    image: venkata040/mongodb:v1
    container_name: mongodb
  catalogue:
    image: venkata040/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: venkata040/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: venkata040/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: venkata040/mysql:v1
    container_name: mysql
  shipping:
    image: venkata040/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq: 
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  
